title: Introduction to golang
description: A course to give basic introduction of golang
template:
  repo: intro-golang-template
  name: intro-golang
  description: 'A robot powered training repository :robot:'
before:
  - type: updateBranchProtection
  - type: createIssue
    title: Welcome to Golang
    body: 00_setup.md
    comments:
      - 00_open-pr.md

steps:

  # Step 1: User opens a PR after setup repo locally
  - title: Open a pull request
    description: Welcome to Golang, let's get started.
    event: pull_request.opened
    link: '{{ repoUrl }}/issues/1'
    actions:
      # Close the previous opened issue
      - type: closeIssue
        issue: Welcome to Golang

      # Once the issue 1 closed, give instruction to learner
      - type: respond
        with: 01_hello-world.md
        issue: 2
      
      # Give instruction to learner to make some changes
      - type: createPullRequestComment
        body: 01_hello-world-activity.md

        # The file property is based on the template file
        file: src/01_hello-world/main.go
        position: 7

  # Step 2: User modified the Hello World program
  - title: Hello World
    description: Modify the "Hello World" program to print something else
    event: push
    link: '{{ repoUrl }}/issues/2'
    actions:
      # Check whether the changes pushed to changes branch or not
      - type: gate
        left: '%payload.ref%'
        operator: ===
        right: refs/heads/changes
     
      - type: getPullRequest
        pullRequest: 2
        action_id: metaPR2
      
      - type: getFileContents
        action_id: fileContents
        filename: 'src/01_hello-world/main.go'
      
      # Using regex to check the file content
      - type: gate
        left: '/\("Hello.*?"\)/gm'
        operator: test
        right: '%actions.fileContents%'
        else:
          - type: respond
            with: 01e_hello-world.md
            issue: 2
      
      # Respond to next instruction
      - type: respond
        with: 02_variables.md
        issue: 2

      - type: createPullRequestComment
        body: 02_variables-activity.md
        file: 'src/02_variables/main.go'



tags:
  - golang
